function J = J(in1,in2)
%J
%    J = J(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    06-Dec-2021 18:24:15

l1 = in1(1,:);
l2 = in1(2,:);
l3 = in1(3,:);
q1 = in2(1,:);
q2 = in2(2,:);
q3 = in2(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t2.*t3;
t9 = t2.*t6;
t10 = t3.*t5;
t11 = t5.*t6;
t12 = l2.*t8;
t13 = l2.*t9;
t14 = l2.*t10;
t15 = l2.*t11;
t16 = -t11;
t20 = t9+t10;
t17 = -t13;
t18 = -t14;
t19 = -t15;
t21 = t8+t16;
t22 = t7.*t20;
t23 = l3.*t4.*t20;
t24 = l3.*t22;
t25 = t4.*t21;
t26 = -t22;
t28 = -t23;
t29 = l3.*t7.*t21;
t27 = l3.*t25;
t30 = -t24;
t31 = -t29;
t32 = t25+t26;
J = reshape([t17+t18+t28+t31-l1.*t5,t12+t19+t27+t30+l1.*t2,0.0,0.0,0.0,t32,t17+t18+t28+t31,t12+t19+t27+t30,0.0,0.0,0.0,t32,t28+t31,t27+t30,0.0,0.0,0.0,t32],[6,3]);
