function J_pi = J_pi(in1,in2)
%J_PI
%    J_PI = J_PI(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    06-Dec-2021 18:24:15

q1 = in2(1,:);
q2 = in2(2,:);
q3 = in2(3,:);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t2.*t3;
t9 = t2.*t6;
t10 = t3.*t5;
t11 = t5.*t6;
t12 = -t11;
t13 = t9+t10;
t14 = t8+t12;
J_pi = reshape([t2,t5,0.0,0.0,0.0,0.0,t14,t13,0.0,0.0,0.0,0.0,t4.*t14-t7.*t13,t4.*t13+t7.*t14,0.0,0.0,0.0,0.0],[6,3]);
